Dev ensprod 8249
Ensembl/ensembl-metadata-api pull request #10
Opened 2022-09-30 00:02 UTC by dpopleton

Added a couple tests and a test database.
The classes:

> load_database
> BaseAdapter
> ReleaseAdapter

have been converted to ORM in api.py.
The remainder of the classes within the file need to be converted

Please leave me with comments so I can improve my style and methods for the future.

2022-09-30 12:50 UTC, marcoooo commented on .python-version
> +ensembl_metadata_api
Not sure this file should be included in PR. What is it for?

2022-09-30 12:59 UTC, vinay-ebi commented on src/ensembl/production/metadata/models.py
> +    uri = Column(String(64), nullable=False)
OnetoMany relationship needed between EnsemblSite to EnsemblReleases ?

2022-09-30 13:01 UTC, marcoooo requested changes
I still can't really see the ManyToMany relationships as we discussed and detailed here: https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#many-to-many
We'll need to discuss this pattern

2022-10-07 10:43 UTC, marcoooo approved these changes

2022-10-08 01:55 UTC, merged