Development sqlalchemy
Ensembl/ensembl-metadata-api pull request #8
Opened 2022-09-26 08:45 UTC by dpopleton

2022-09-26 08:52 UTC, vinay-ebi commented on requirements.in
> +fastapi
can remove fastapi for now

2022-09-26 08:53 UTC, vinay-ebi commented on src/ensembl/production/metadata/api.py
> +import models
test case failed as models module not found either you can use relative import  or `import  enseml.production.metadata.models`

2022-09-27 11:02 UTC, marcoooo commented on src/ensembl/production/metadata/api.py
>  import sqlalchemy as db
please add the NOTICE statemtn

2022-09-30 13:02 UTC, marcoooo requested changes
See my comments is the other PR #10

2022-10-08 01:56 UTC, merged