Feature/compara usecase tests
Ensembl/ensembl-metadata-api pull request #85
Opened 2024-04-05 08:38 UTC by marcoooo

Added first row of Compara dedicated functions / tests.

2024-04-05 08:53 UTC, dpopleton requested changes

2024-04-05 08:53 UTC, dpopleton commented on src/ensembl/production/metadata/api/models/genome.py
> +    genebuild_version = Column(String(20), nullable=True, unique=False)
The 20 characters for genebuild version may not be enough. Be sure to check with Metazoa as to how they are planning to use it.

2024-04-15 09:50 UTC, ens-sb approved these changes

2024-04-18 09:00 UTC, dpopleton approved these changes

2024-04-18 09:05 UTC, merged